apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-test
  labels:
    app: llm-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-test
  template:
    metadata:
      labels:
        app: llm-test
    spec:
      containers:
      - name: llm-test
        image: huggingface/transformers-pytorch-gpu:latest
        command: ["/bin/sh", "-c", "sleep 1000000"]
        resources:
          requests:
            nvidia.com/gpu: 1
            cpu: 8
            memory: 32Gi
          limits:
            nvidia.com/gpu: 1
            cpu: 10
            memory: 36Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-RTX-A6000

